services:
  app:
    image: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
#    ports:
#      - 3000:80
    container_name: frontend-prod
  api:
    image: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
#    ports:
#      - 3001:3001
    container_name: api-prod
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    container_name: reverse_proxy
    depends_on:
      - app
      - api
    